version: '3.8'
services:
  cleanapi:
    build: .
    ports:
      - "8990:8000"
    env_file:
      - .env
    networks:
      - assessment-network
    volumes:
      - ./app:/app/app

networks:
  assessment-network:
    driver: bridge
